Require Import Abstraction.
Require Import ssrbool ssreflect.
Require Import autoreflect.
Require Import Quadrivalent.

Include Quadrivalent.

(** This file extends quadrivalent with lattice operations. *)

(** We use the [quad_all] definition to prevents the unification to
duplicate f in every instance. This makes the terms generated by
autoreflect smaller. *)
Definition quad_all (f : quadrivalent -> bool) : bool :=
  f QBottom && f QTrue && f QFalse && f QTop.

Instance AutoReflect_forall_quadrivalent fP fb
  `{forall q:quadrivalent, (AutoReflect (fP q) (fb q))}:
  AutoReflect (forall q:quadrivalent, fP q) (quad_all fb).
Proof.
  apply: (iffP (andPP (andPP (andPP idP idP) idP) idP)).
  - move=> [[[H1 H2] H3] H4] q. apply: H. case:q; done.
  - move=> Hq. repeat split; by apply /H.
Qed.

Definition dec (q1 q2 : quadrivalent) : {q1 = q2} + {q1 <> q2}.
Proof. decide equality. Defined.

Definition eqb q1 q2 := if dec q1 q2 then true else false.

Lemma eqP q1 q2 : reflect (q1 = q2) (eqb q1 q2).
Proof. rewrite /eqb.
       by case: dec; constructor.
Qed.

Definition equal := eqb.

(** Simple decidable equality: a direct pattern match that reduces
    even when the arguments are symbolic [match] expressions.
    Unlike [eqb], this avoids the [decide equality] complexity
    that blocks [solve_with_autoreflect]. *)
Definition qv_eqb (q1 q2 : quadrivalent) : bool :=
  match q1, q2 with
  | QBottom, QBottom => true
  | QTrue, QTrue => true
  | QFalse, QFalse => true
  | QTop, QTop => true
  | _, _ => false
  end.

Lemma qv_eqbP (q1 q2 : quadrivalent) : reflect (q1 = q2) (qv_eqb q1 q2).
Proof.
  case: q1; case: q2 => //=; constructor; try reflexivity;
  by move=> H; discriminate H.
Qed.

Global Instance AutoReflect_qv_eq q1 q2 : AutoReflect (q1 = q2) (qv_eqb q1 q2) | 10.
Proof. apply: AutoReflect_base. apply: qv_eqbP. Qed.


  
(* Global Instance elem_of_gamma (q:quadrivalent):  FinSet (propset bool) bool. *)

Definition join (x y:quadrivalent) : quadrivalent :=
  match x,y with
  | QTop, _ | _, QTop => QTop    
  | QBottom, a | a, QBottom => a
  | QTrue, QTrue => QTrue
  | QFalse, QFalse => QFalse
  | QTrue, QFalse | QFalse, QTrue => QTop
  end.
Lemma join_exact: binary_exact qv qv qv join (∪).
Proof.
  move=> q1 q2.
  rewrite /ExactlyRepresents. unfold_set.
  move: q1 q2.
  (* evar(k:bool). eassert(AutoReflect (forall (q1 q2 : qv) (c : bool), c ∈ γ (join q1 q2) <-> c ∈ γ q1 ∪ γ q2) ?k) by apply _. *)
  solve_with_autoreflect.
Qed.

Definition meet (x y:quadrivalent) : quadrivalent :=
  match x,y with
  | QBottom, _ | _, QBottom => QBottom
  | QTop, a | a, QTop => a
  | QTrue, QTrue => QTrue
  | QFalse, QFalse => QFalse
  | QTrue, QFalse | QFalse, QTrue => QBottom
  end.
Lemma meet_exact: binary_exact qv qv qv meet (∩).
Proof.
  move=> q1 q2.
  rewrite /ExactlyRepresents. unfold_set.
  move: q1 q2.
  solve_with_autoreflect.
Qed.



